outputDir:         /home/everett/projects/AAVengeR2/out
softwareDir:       /home/everett/projects/AAVengeR2
sampleConfigFile:  /home/everett/projects/AAVengeR_runs/configs/sampleConfig.Sabatino.tsv




demultiplex_outputDir: demultiplex
demultiplex_CPUs: 20
demultiplex_qualtrim_code: '5'
demultiplex_qualtrim_minLength: 100
demultiplex_anchorReadsFile: /home/everett/projects/AAVengeR/data/testData/R2.test.fastq.gz
demultiplex_adriftReadsFile: /home/everett/projects/AAVengeR/data/testData/R1.test.fastq.gz
demultiplex_index1ReadsFile: /home/everett/projects/AAVengeR/data/testData/I1.test.fastq.gz
demultiplex_correctGolayIndexReads: TRUE
demultiplex_correctGolayIndexReads_CPUs: 20
demultiplex_sequenceChunkSize: 100000
demultiplex_index1ReadFileMaxMismatch: 1
demultiplex_useAdriftReadUniqueLinkers: TRUE
demultiplex_adriftReadLinkerBarcodeMaxMismatch: 2


createUniqueFasta_CPUs: 20
createUniqueFasta_outputDir: uniqueFasta
createUniqueFasta_inputDir:  demultiplex


vectorFilter_inputDir :  uniqueFasta
vectorFilter_outputDir:  vectorFilter
vectorFilter_outputFile: vectorFilter.rds
vectorFilter_CPUs: 25
vectorFilter_anchorReadSampleLength: 25
vectorFilter_percentID: 98
vectorFilter_percentCoverage: 90

mapLeaderSequences_inputDir :  uniqueFasta
mapLeaderSequences_outputDir:  mapLeaderSequences
mapLeaderSequences_outputFile: mappings.rds
mapLeaderSequences_CPUs: 25
mapLeaderSequences_alignmentChunkSize: 10000
mapLeaderSequences_minAlignmentLength: 10
mapLeaderSequences_minAlignmentPercentID: 95


alignReads_outputDir: alignReads
alignReads_inputDir:  uniqueFasta
alignReads_vectorFilterOutputFile: vectorFilter/vectorFilter.rds
alignReads_mapLeaderSequencesOutputFile: mapLeaderSequences/mappings.rds
alignReads_anchorReadAlignmentsOutputFile: anchorReadAlignments.rds
alignReads_adriftReadAlignmentsOutputFile: adriftReadAlignments.rds
alignReads_CPUs: 25
alignReads_alignmentChunkSize: 5000
alignReads_minAnchorReadLengthPostTrim: 25
alignReads_minAdriftReadLengthPostTrim: 25
alignReads_genomeAlignment_minPercentID: 98
alignReads_genomeAlignment_anchorReadEnd_maxUnaligned: 3
alignReads_genomeAlignment_adriftReadEnd_maxUnaligned: 3
alignReads_genomeAlignment_anchorReadMinStart: 10
alignReads_genomeAlignment_adriftReadMaxStart: 3
alignReads_performSecondGenomeAlignment: TRUE

buildFragments_CPUs: 25
buildFragments_outputDir: fragments
buildFragments_outputFile: fragments.rds
buildFragments_anchorReadsAlignmentFile: alignReads/anchorReadAlignments.rds
buildFragments_adriftReadsAlignmentFile: alignReads/adriftReadAlignments.rds
buildFragments_duplicateReadFile: uniqueFasta/dupReadPairMap.tsv
buildFragments_maxAlignmentsPerRead: 100
buildFragments_minFragLength: 25
buildFragments_maxFragLength: 2500
buildFragments_representativeSeqCalc_maxReads: 5000
buildFragments_representativeSeqCalc_CPUs: 5
buildFragments_maxLeaderSeqDiffScore: 0.15
buildFragments_assemblyConflictResolution: 0.66


standardizeFragments_CPUs: 10
standardizeFragments_inputFile: fragments/fragments.rds
standardizeFragments_outputDir: standardizeFragments
standardizeFragments_outputFile: stdFragments.rds
standardizeFragments_standardizeSitesBy: subject
standardizeFragments_standardizeBreaksBy: replicate
standardizeFragments_maxLeaderSeqDiffScore: 0.15


# chrX,122897024,123043178|chr1,107856070,107856080
buildSites_inputFile: standardizeFragments/stdFragments.rds
buildSites_outputDir: buildSites
buildSites_excludeSites: chrX,122897024,123043178


command_python2:     /usr/bin/python2
command_blat:        /home/everett/ext/blat
command_cutadapt:    /usr/local/bin/cutadapt
command_muscle:      /home/everett/ext/muscle
command_makeblastdb: /home/everett/ext/blast+/bin/makeblastdb
command_blastn:      /home/everett/ext/blast+/bin/blastn
