Rscript:           /home/opt/R-3.4.0/lib/R/bin/Rscript
softwareDir:       /home/everett/projects/AAVengeR2
outputDir:         /home/everett/projects/Sabatino_canine_hemophilia_AAV/out
sampleConfigFile:  /home/everett/projects/Sabatino_canine_hemophilia_AAV/sampleConfig.tsv
modules:           
                   - demultiplex.R
                   - prepReads.R
                   - alignReads.R 
                   - buildFragments.R
                   - standardizeFragments.R
                   - buildSites.R
                   - mapSiteLeaderSequences.R
             
#----------------------------------------------------------------------------

demultiplex_outputDir: demultiplex
demultiplex_CPUs: 20
demultiplex_RC_I1_barcodes: FALSE
demultiplex_qualtrim_code: '5'
demultiplex_qualtrim_minLength: 50
demultiplex_anchorReadsFile: /home/everett/projects/canine_hemophilia_AAV/data/sequencingData/Undetermined_S0_L001_R2_001.fastq.gz
demultiplex_adriftReadsFile: /home/everett/projects/canine_hemophilia_AAV/data/sequencingData/Undetermined_S0_L001_R1_001.fastq.gz
demultiplex_index1ReadsFile: /home/everett/projects/canine_hemophilia_AAV/data/sequencingData/Undetermined_S0_L001_I1_001.fastq.gz
demultiplex_correctGolayIndexReads: TRUE
demultiplex_sequenceChunkSize: 100000
demultiplex_index1ReadMaxMismatch: 6  # All samples have the same barcode, use a high value to accept all codes.
demultiplex_useAdriftReadUniqueLinkers: TRUE
demultiplex_adriftReadLinkerBarcodeMaxMismatch: 1

prepReads_CPUs: 20
prepReads_outputDir: prepReads
prepReads_inputDir:  demultiplex
prepReads_minAnchorReadLength: 40
prepReads_minAdriftReadLength: 30
prepReads_minAlignmentPercentID: 90
prepReads_minAlignmentLength: 15
prepReads_vectorAlignmentTestLength: 25
prepReads_vectorAlignmentTestLength_drift: 2
prepReads_vectorAlignmentChunkSize: 25000

alignReads_outputDir: alignReads
alignReads_inputDir:  prepReads/final
alignReads_mapLeaderSequencesOutputFile: prepReads/alignments.rds
alignReads_anchorReadAlignmentsOutputFile: anchorReadAlignments.rds
alignReads_adriftReadAlignmentsOutputFile: adriftReadAlignments.rds
alignReads_CPUs: 20
alignReads_alignmentChunkSize: 10000
alignReads_minAnchorReadLengthPostTrim: 25
alignReads_minAdriftReadLengthPostTrim: 25
alignReads_genomeAlignment_minPercentID: 97
alignReads_genomeAlignment_blatStepSize: 9
alignReads_genomeAlignment_blatTileSize: 11
alignReads_genomeAlignment_anchorReadEnd_maxUnaligned: 3
alignReads_genomeAlignment_adriftReadEnd_maxUnaligned: 3
alignReads_genomeAlignment_anchorReadMinStart: 10
alignReads_genomeAlignment_adriftReadMaxStart: 3
alignReads_performSecondGenomeAlignment: TRUE

buildFragments_CPUs: 25
buildFragments_outputDir: fragments
buildFragments_outputFile: fragments.rds
buildFragments_anchorReadsAlignmentFile: alignReads/anchorReadAlignments.rds
buildFragments_adriftReadsAlignmentFile: alignReads/adriftReadAlignments.rds
buildFragments_duplicateReadFile: prepReads/duplicateReads.rds
buildFragments_idGroup_size: 1000
buildFragments_maxAlignmentsPerRead: 500
buildFragments_minFragLength: 25
buildFragments_maxFragLength: 2500
buildFragments_representativeSeqCalc_maxReads: 5000
buildFragments_representativeSeqCalc_CPUs: 5
buildFragments_maxLeaderSeqDiffScore: 0.15
buildFragments_assemblyConflictResolution: 0.66

standardizeFragments_CPUs: 10
standardizeFragments_inputFile: fragments/fragments.rds
standardizeFragments_outputDir: standardizeFragments
standardizeFragments_outputFile: stdFragments.rds
standardizeFragments_standardizeSitesBy: subject
standardizeFragments_standardizeBreaksBy: replicate
standardizeFragments_maxLeaderSeqDiffScore: 0.15


# Example buildSites_excludeSites parameter: chrX,122897024,123043178|chr1,107856070,107856080
buildSites_inputFile: standardizeFragments/stdFragments.rds
buildSites_outputDir: buildSites
buildSites_outputFile: sites.rds
buildSites_excludeSites: chrX,122897024,123043178

mapSiteLeaderSequences_outputDir:  mapSiteLeaderSequences
mapSiteLeaderSequences_inputFile:  buildSites/sites.rds
mapSiteLeaderSequences_outputFile: sites.rds
mapSiteLeaderSequences_CPUs: 25
mapSiteLeaderSequences_alignmentChunkSize: 10000
mapSiteLeaderSequences_minAlignmentLength: 10
mapSiteLeaderSequences_minAlignmentPercentID: 90





command_python2:     /usr/bin/python2
command_blat:        /home/everett/ext/blat
command_cutadapt:    /usr/local/bin/cutadapt
command_muscle:      /home/everett/ext/muscle
command_makeblastdb: /home/everett/ext/blast+/bin/makeblastdb
command_blastn:      /home/everett/ext/blast+/bin/blastn
