# AAVengeR configuration file.

# Required inputs that should be updated for each run.
#~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
mode: integrase                       # (integrase, AAV, transposase, or manual)

core_CPUs: 15

outputDir: output
softwareDir: /home/ubuntu/AAVengeR

databaseConfigFile: /home/ubuntu/.my.cnf
databaseConfigGroup: none

sequencingRunID: 200101_M03500_0001_000000000-ABCXY

demultiplex_anchorReadsFile: Undetermined_S0_R2_001.fastq.gz
demultiplex_adriftReadsFile: Undetermined_S0_R1_001.fastq.gz
demultiplex_index1ReadsFile: Undetermined_S0_I1_001.fastq.gz
demultiplex_sampleDataFile:  sampleData.tsv

modules:
   - core
   - callNearestGenes
   - annotateRepeats


# Additional parameters.
# ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
Rscript: /usr/bin/Rscript
compressDataFiles: FALSE
processAdriftReadLinkerUMIs: FALSE
core_keepIntermediateFiles: FALSE
core_applyCoreCPUsToAllModules: TRUE


# Demultiplex module.
# ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
demultiplex_CPUs: 15
demultiplex_outputDir: demultiplex
demultiplex_replicateMergingInstructions: none
demultiplex_level: unique                          # (all, unique, or clustered)
demultiplex_quickAlignFilter: FALSE
demultiplex_useAdriftReadUniqueLinkers: TRUE
demultiplex_requirePostUmiLinker: TRUE
demultiplex_requirePostUmiLinker_maxMismatch: 2
demultiplex_RC_I1_barcodes: FALSE
demultiplex_RC_I1_barcodes_auto: TRUE
demultiplex_qualtrim_code: '+'
demultiplex_qualtrim_halfWidth: 3
demultiplex_qualtrim_events: 2
demultiplex_qualtrim_minLength: 50
demultiplex_correctGolayIndexReads: FALSE
demultiplex_sequenceChunkSize: 300000
demultiplex_index1ReadMaxMismatch: 1
demultiplex_adriftReadLinkerBarcodeMaxMismatch: 1
demultiplex_anchorReadStartSeq.maxMisMatch: 1
demultiplex_exportFASTQ: FALSE
demultiplex_quickAlignFilter_minPercentID: 97
demultiplex_quickAlignFilter_minMatches: 30
demultiplex_mergeSimilarReadPairsParams: -c 0.98 -d 0 -M 0 -g 1 -r 0 -ap 1 -G 0 -n 5 -gap -10 -gap-ext -5 -aS 0.98 -aL 0.98


# prepRead module.
# ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
prepReads_CPUs: 15
prepReads_outputDir: prepReads
prepReads_readsTable:  demultiplex/reads.rds
prepReads_excludeAnchorReadVectorHits: TRUE
prepReads_excludeAdriftReadVectorHits: FALSE
prepReads_vectorAlignmentTestLength: 25
prepReads_vectorAlignmentTest_minPercentCoverage: 90
prepReads_vectorAlignmentTest_minPercentID: 90
prepReads_minAnchorReadLength: 30
prepReads_minAdriftReadLength: 30
prepReads_buildReadMaps_blastReconstruction: TRUE
prepReads_mapLeaderSeqsMinAlignmentLength: 15
prepReads_mapLeaderSeqsMinPercentID: 95
prepReads_mapLeaderSeqsMaxGapBetweenAlignments: 5
prepReads_buildReadMaps_minMapStartPostion: 5
prepReads_useDefaultHMMsettings: TRUE
prepReads_HMMsearchReadStartPos: 1
prepReads_HMMsearchReadEndPos:  100
prepReads_HMMmaxStartPos: 5
prepReads_HMMminFullBitScore: 20
prepReads_HMMmatchEnd: TRUE
prepReads_HMMmatchTerminalSeq: CA
prepReads_forceAnchorReadStartSeq: FALSE
prepReads_limitLeaderSeqsWithQuickAlignFilter: TRUE
prepReads_additionalAnchorReadOverReadingSeqs: none
prepReads_cutAdaptErrorRate: 0.15


# alignReads module.
# ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
alignReads_CPUs: 15
alignReads_outputDir: alignReads
alignReads_inputFile: prepReads/reads.rds
alignReads_blat_fastMap: FALSE
alignReads_blatUseOocFile: FALSE
alignReads_genomeAlignment_anchorRead_maxStartPos: 3
alignReads_genomeAlignment_adriftRead_maxStartPos: 3
alignReads_genomeAlignment_minPercentID: 95
alignReads_genomeAlignment_blatStepSize: 5
alignReads_genomeAlignment_blatTileSize: 11
alignReads_genomeAlignment_blatRepMatch: 3000
alignReads_genomeAlignment_blatMaxtNumInsert: 1
alignReads_genomeAlignment_blatMaxqNumInsert: 1
alignReads_genomeAlignment_blatMaxtBaseInsert: 1
alignReads_genomeAlignment_blatMaxqBaseInsert: 1
alignReads_genomeAlignment_anchorReadEnd_maxUnaligned: 5
alignReads_genomeAlignment_adriftReadEnd_maxUnaligned: 5


# buildFragments module.
# ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
buildFragments_CPUs: 15
buildFragments_outputDir: buildFragments
buildFragments_anchorReadsAlignmentFile: alignReads/anchorReadAlignments.rds
buildFragments_adriftReadsAlignmentFile: alignReads/adriftReadAlignments.rds
buildFragments_idGroup_size: 500
buildFragments_maxReadAlignments: 1500
buildFragments_salvageReadsBeyondMaxNumAlignments: TRUE
buildFragments_minFragLength: 40
buildFragments_maxFragLength: 100000
buildFragments_randomLinkerID_minReadCountToSegreagate: 10
buildFragments_randomLinkerID_minSingleSampleMajorityPercent: 90


# buildStdFragments module.
# ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
buildStdFragments_CPUs: 15
buildStdFragments_inputFile: buildFragments/fragments.rds
buildStdFragments_outputDir: buildStdFragments
buildStdFragments_autoPullTrialSamples: FALSE
buildStdFragments_trialSubjectList: none
buildStdFragments_randomIDdupReadMult: 3
buildStdFragments_randomIDdupAbundMult: 2
buildStdFragments_clusterLeaderSeqs: FALSE
buildStdFragments_standardizeIntegrationPositions: TRUE
buildStdFragments_standardizeBreakPositions: TRUE
buildStdFragments_standardizeBreakPositionsWithin: replicates
buildStdFragments_intSiteStdWindowWidth: 5
buildStdFragments_breakPointStdWindowWidth: 3
buildStdFragments_minReadsPerFrag: 1
buildStdFragments_maxFragLength: 3000
buildStdFragments_createMultiHitClusters: TRUE
buildStdFragments_salvageMultiHitReads: TRUE
buildStdFragments_UMIminPercentReads: 15
buildStdFragments_remnantClusterParams: -c 0.85 -d 0 -M 0 -g 1 -r 0 -ap 1 -G 0 -n 5 -gap -5 -gap-ext -1 -aS 0.85 -aL 0.85
buildStdFragments_evalFragAnchorReadSeqs: TRUE
buildStdFragments_fragEvalAnchorReadTestLen: 30
buildStdFragments_fragClusterParams: -c 0.87 -d 0 -M 0 -g 1 -r 0 -ap 1 -G 0 -n 5 -gap -10 -gap-ext -5 -aS 0.95 -aL 0.95
buildStdFragments_fragEvalAnchorReadMinAbundDiff: 5
buildStdFragments_fragEvalAnchorReadMinReadMult: 10


# buildSites module.
# ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
buildSites_CPUs: 15
buildSites_inputFile: buildStdFragments/stdFragments.rds
buildSites_outputDir: buildSites
buildSites_enableDualDetection: TRUE
buildSites_dualDetectWidth: 6
buildSites_integraseCorrectionDist: 0
buildSites_sumSonicBreaksWithin: samples


# annotateRepeat module.
# ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
annotateRepeats_CPUs: 15
annotateRepeats_inputFile: callNearestGenes/sites.rds
annotateRepeats_outputDir: annotateRepeats
annotateRepeats_addAfter: nRepsObs


# callNearestGenes module.
# ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
callNearestGenes_CPUs: 15
callNearestGenes_inputFile: core/sites.rds
callNearestGenes_outputDir: callNearestGenes
callNearestGenes_addAfter: nRepsObs
callNearestGenes_columnPrefix: none
callNearestGenes_geneList: none
callNearestGenes_TU_position: either
callNearestGenes_boundaries:
  hg38:
    TUs:   hg38.TUs.rds
    exons: hg38.exons.rds
  hs1:
    TUs:   hs1.TUs.rds
    exons: hs1.exons.rds
  sacCer3:
    TUs:   sacCer3.TUs.rds
    exons: sacCer3.exons.rds
  canFam3:
    TUs:   canFam3.humanXenoRef.TUs.rds
    exons: canFam3.humanXenoRef.exons.rds
  macFas5:
    TUs:   macFas5.humanXenoRef.TUs.rds
    exons: macFas5.humanXenoRef.exons.rds


# mapSiteLeaderSequences module.
# ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
mapSiteLeaderSequences_CPUs: 15
mapSiteLeaderSequences_outputDir: mapSiteLeaderSequences
mapSiteLeaderSequences_inputFile: annotateRepeats/sites.rds
mapSiteLeaderSequences_addAfter: repLeaderSeq
mapSiteLeaderSequences_minLocalAlignmentLength: 12
mapSiteLeaderSequences_minAlignmentPercentID: 90
mapSiteLeaderSequences_minAlignmentLength: 15
mapSiteLeaderSequences_maxMissingTailNTs: 5


# predictPCRartifacts module.
# ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
predictPCRartifacts_CPUs: 15
predictPCRartifacts_inputFile: callNearestGenes/sites.rds
predictPCRartifacts_outputDir: predictPCRartifacts
predictPCRartifacts_adjacentSeqLength: 14
predictPCRartifacts_minReportHalfMatches: 5
predictPCRartifacts_minReportMatches: 10
predictPCRartifacts_maxAlnGaps: 1
predictPCRartifacts_wordSize: 5
predictPCRartifacts_gapOpeningPenalty: 10
predictPCRartifacts_gapExtensionPenalty: 5
predictPCRartifacts_addAfter: posid


# barcodeAssocLinkers module.
# ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
barcodeAssocLinkers_outputDir: barcodeAssocLinkers
barcodeAssocLinkers_sampleDataFile:  data/sampleData.tsv
barcodeAssocLinkers_adriftReadsFile: data/Undetermined_S0_R1_001.fastq.gz
barcodeAssocLinkers_index1ReadsFile: data/Undetermined_S0_I1_001.fastq.gz
barcodeAssocLinkers_nCodes: 50
barcodeAssocLinkers_excludePolyG_index1BarCodes: TRUE
barcodeAssocLinkers_adriftReadUniqueLinkerLength: 20


# buildAAVremnantPlots module.
# ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
buildAAVremnantPlots_outputDir: buildAAVremnantPlots
buildAAVremnantPlots_inputFile: mapSiteLeaderSequences/sites.rds
buildAAVremnantPlots_NTbinSize: 3
buildAAVremnantPlots_ITRlength: 197
buildAAVremnantPlots_ITRseqStart: 57
buildAAVremnantPlots_ITRdumbellTip1: 125
buildAAVremnantPlots_ITRdumbellTip2: 147
buildAAVremnantPlots_plotOutputWidthInches: 10


# anchorReadRearrangements module.
# ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
anchorReadRearrangements_CPUs: 15
anchorReadRearrangements_outputDir: anchorReadRearrangements
anchorReadRearrangements_inputFile: demultiplex/reads.rds
anchorReadRearrangements_vectorLeaderSeqFilterLength: 12
anchorReadRearrangements_vectorLeaderSeqFilterMaxMismatch: 1
anchorReadRearrangements_qualtrim_events: 2
anchorReadRearrangements_qualtrim_code: '5'
anchorReadRearrangements_qualtrim_halfWidth: 5
anchorReadRearrangements_minReadOverlapNTs: 20
anchorReadRearrangements_maxReadOverlapPval: 0.001
anchorReadRearrangements_anchorReadCutPos: 200
anchorReadRearrangements_requireReadPairOverlap: TRUE
anchorReadRearrangements_minReadsPerAltStruct: 2
anchorReadRearrangements_cutAdaptErrorRate: 0.15
anchorReadRearrangements_minAlignmentLength: 10
anchorReadRearrangements_minAlignmentPercentID: 90
anchorReadRearrangements_maxMissingTailNTs: 11
anchorReadRearrangements_readEndAlignmentTestLength: 12
anchorReadRearrangements_readEndAlignmentTestMinMatch: 11
anchorReadRearrangements_clusterParams: -c 0.90 -d 0 -aS 0.93 -M 0 -g 1 -r 0 -ap 1 -G 0 -n 5 -gap -5 -gap-ext -1
anchorReadRearrangements_expectedSeqs:
  Sabatino_PMC7855056_splitChain_plasmids.fasta:
    - CATGCTCTAGGAAGATCCAGGTTAATTTTTAAAAAGCAGTCAAAAGTCCAAGTGGCCCTTGGCAGCATTTACTCTCTCTGTTTGCTCTGGTTAATAATCTCAGGAGCACAAACATTCCAGATCCAGGTTAATTTTTAAAAAGCAGTCAAAAGTCCAAGTGGCCCTTGGCAGCATTTACTCTCTCTGTTTGCTCTGGTTAATAATCTCAGGAGCACAAACATTCCAGATCCGGCGCGCCAGGGCTGGAAGCTACCTTTGACATCATTTCCTCTGCGAATGCATGTATAATTTCTACAGAACCTATTAGAAAGGATCACCCAGCCTCTGCTTTTGTACAACTTTCCCTTAAAAAACTGCCAATTCCACTGCTGTTTGGCCCAATAGTGAGAACTTTTTCCTGCTGCCTCTTGGTGCTTTTGCCTATGGCCCCTATTCTGCCTGCTGAAGACACTCTTGCCAGCATGGACTTAAACCCCTCCAGCTCTGACAATCCTCTTTCT
    - CATGCTCTAGGAAGATCCTTATCGATTTTACCACATTTGTAGAGGTTTTACTTGCTTTAAAAAACCTCCCACATCTCCCCCTGAACCTGAAACATAAAATGAATGCAATTGTTGTTGTTAACTTGTTTATTGCAGCTTATAATGGTTACAAATAAAGCAATAGCATCACAAATTTCACAAATAAAGCATTTTTTTCACTGCATTCTAGTTGTGGTTTGTCCAAACTCATCAATGTATCTTATCATGTCTGCTCGAAGCGGCCGCTCTAGATCAGGCGGGCTGCTGGGTGTCGCAGCCCAGGACCTCCAGCCTCAGGGCGATGTGGTGCGCCCAGCTCTGCGGGTGCAGGCGCACGTAGCGAGCCACCAGCGGGGGTTCGAGACGGTTCCGCACAGGCGTGGAGGAGTCCCGGTTTCCCTGGAAGACCTTGACTTTGCCATTCTGAAGAAACAGAGTCCAGTTATGGCCATCTTGACTACTGGAGATGAGGAACTCCTTCA
    - CATGCTCTAGGAAGATCCTTATCGATTTTACCACATTTGTAGAGGTTTTACTTGCTTTAAAAAACCTCCCACATCTCCCCCTGAACCTGAAACATAAAATGAATGCAATTGTTGTTGTTAACTTGTTTATTGCAGCTTATAATGGTTACAAATAAAGCAATAGCATCACAAATTTCACAAATAAAGCATTTTTTTCACTGCATTCTAGTTGTGGTTTGTCCAAACTCATCAATGTATCTTATCATGTCTGCTCGAAGCGGCCGCTCAGCCCTTGTTTCTTTCTATTGCTCCACGTGAATGGTCATCGGCTCTATCTGTGGCCTCTCGGAGATCAGATAAGAACAGTCCACGTGGAGTAGGATTCTGTCCCAACAGCATCAACAAATCACTAGAGGAGACACTTTGTGCTTTAATCAGCTGTGTTCTTTCTCCAGATTGAAGGTCAATCTTCTCTATGTCATTTTCTGGAGTTGTGGTGGCTTTCAATTGCTTTTCCTTAG
  Sabatino_PMC7855056_lightChain_plasmid.fasta:
    - CATGCTCTAGGAAGATCCAGGTTAATTTTTAAAAAGCAGTCAAAAGTCCAAGTGGCCCTTGGCAGCATTTACTCTCTCTGTTTGCTCTGGTTAATAATCTCAGGAGCACAAACATTCCAGATCCAGGTTAATTTTTAAAAAGCAGTCAAAAGTCCAAGTGGCCCTTGGCAGCATTTACTCTCTCTGTTTGCTCTGGTTAATAATCTCAGGAGCACAAACATTCCAGATCCGGCGCGCCAGGGCTGGAAGCTACCTTTGACATCATTTCCTCTGCGAATGCATGTATAATTTCTACAGAACCTATTAGAAAGGATCACCCAGCCTCTGCTTTTGTACAACTTTCCCTTAAAAAACTGCCAATTCCACTGCTGTTTGGCCCAATAGTGAGAACTTTTTCCTGCTGCCTCTTGGTGCTTTTGCCTATGGCCCCTATTCTGCCTGCTGAAGACACTCTTGCCAGCATGGACTTAAACCCCTCCAGCTCTGACAATCCTCTTTCT
    - CATGCTCTAGGAAGATCCTTATCGATTTTACCACATTTGTAGAGGTTTTACTTGCTTTAAAAAACCTCCCACATCTCCCCCTGAACCTGAAACATAAAATGAATGCAATTGTTGTTGTTAACTTGTTTATTGCAGCTTATAATGGTTACAAATAAAGCAATAGCATCACAAATTTCACAAATAAAGCATTTTTTTCACTGCATTCTAGTTGTGGTTTGTCCAAACTCATCAATGTATCTTATCATGTCTGCTCGAAGCGGCCGCTCTAGATCAGGCGGGCTGCTGGGTGTCGCAGCCCAGGACCTCCAGCCTCAGGGCGATGTGGTGCGCCCAGCTCTGCGGGTGCAGGCGCACGTAGCGAGCCACCAGCGGGGGTTCGAGACGGTTCCGCACAGGCGTGGAGGAGTCCCGGTTTCCCTGGAAGACCTTGACTTTGCCATTCTGAAGAAACAGAGTCCAGTTATGGCCATCTTGACTACTGGAGATGAGGAACTCCTTCA
  Sabatino_PMC7855056_heavyChain_plasmid.fasta:
    - CATGCTCTAGGAAGATCCAGGTTAATTTTTAAAAAGCAGTCAAAAGTCCAAGTGGCCCTTGGCAGCATTTACTCTCTCTGTTTGCTCTGGTTAATAATCTCAGGAGCACAAACATTCCAGATCCAGGTTAATTTTTAAAAAGCAGTCAAAAGTCCAAGTGGCCCTTGGCAGCATTTACTCTCTCTGTTTGCTCTGGTTAATAATCTCAGGAGCACAAACATTCCAGATCCGGCGCGCCAGGGCTGGAAGCTACCTTTGACATCATTTCCTCTGCGAATGCATGTATAATTTCTACAGAACCTATTAGAAAGGATCACCCAGCCTCTGCTTTTGTACAACTTTCCCTTAAAAAACTGCCAATTCCACTGCTGTTTGGCCCAATAGTGAGAACTTTTTCCTGCTGCCTCTTGGTGCTTTTGCCTATGGCCCCTATTCTGCCTGCTGAAGACACTCTTGCCAGCATGGACTTAAACCCCTCCAGCTCTGACAATCCTCTTTCT
    - CATGCTCTAGGAAGATCCTTATCGATTTTACCACATTTGTAGAGGTTTTACTTGCTTTAAAAAACCTCCCACATCTCCCCCTGAACCTGAAACATAAAATGAATGCAATTGTTGTTGTTAACTTGTTTATTGCAGCTTATAATGGTTACAAATAAAGCAATAGCATCACAAATTTCACAAATAAAGCATTTTTTTCACTGCATTCTAGTTGTGGTTTGTCCAAACTCATCAATGTATCTTATCATGTCTGCTCGAAGCGGCCGCTCAGCCCTTGTTTCTTTCTATTGCTCCACGTGAATGGTCATCGGCTCTATCTGTGGCCTCTCGGAGATCAGATAAGAACAGTCCACGTGGAGTAGGATTCTGTCCCAACAGCATCAACAAATCACTAGAGGAGACACTTTGTGCTTTAATCAGCTGTGTTCTTTCTCCAGATTGAAGGTCAATCTTCTCTATGTCATTTTCTGGAGTTGTGGTGGCTTTCAATTGCTTTTCCTTAG
  BushmanAAVcontrolsLargestRemnant-plasmid.fasta:
    - TTCCTATCTAGATGCATTCGCGAGGTACCGAGCTCGAATTCACTGGCCGTCGTTTTACAACGTCGTGACTGGGAAAACCCTGGCGTTACCCAACTTAATCGCCTTGCAGCACATCCCCCTTTCGCCAGCTGGCGTAATAGCGAAGAGGCCCGCACCGATCGCCCTTCCCAACAGTTGCGCAGCCTGAATGGCGAATGGCGCCTGATGCGGTATTTTCTCCTTACGCATCTGTGCGGTATTTCACACCGCATATGGTGCACTCTCAGTACAATCTGCTCTGATGCCGCATAGTTAAGCCAGCCCCGACACCCGCCAACACCCGCTGACGCGCCCTGACGGGCTTGTCTGCTCCCGGCATCCGCTTACAGACAAGCTGTGACCGTCTCCGGGAGCTGCATGTGTCAGAGGTTTTCACCGTCATCACCGAAACGCGCGAGACGAAAGGGCCTCGTGATACGCCTATTTTTATAGGTTAATGTCATGATAATAATGGTTTCTTA
  pAAV-GFP-plasmid.fasta:
    - TTCCTTGTAGTTAATGATTAACCCGCCATGCTACTTATCTACGTAGCCATGCTCTAGCGGCCTCGGCCTCTGCATAAATAAAAAAAATTAGTCAGCCATGAGCTTGGCCCATTGCATACGTTGTATCCATATCATAATATGTACATTTATATTGGCTCATGTCCAACATTACCGCCATGTTGACATTGATTATTGACTAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCATATATGGAGTTCCGCGTTACATAACTTACGGTAAATGGCCCGCCTGGCTGACCGCCCAACGACCCCCGCCCATTGACGTCAATAATGACGTATGTTCCCATAGTAACGCCAATAGGGACTTTCCATTGACGTCAATGGGTGGAGTATTTACGGTAAACTGCCCACTTGGCAGTACATCAAGTGTATCATATGCCAAGTACGCCCCCTATTGACGTCAATGACGGTAAATGGCCCGCCTGGCATTATGCCCAGTACAT
    - TTCCTTGTAGTTAATGATTAACCCGCCATGCTACTTATCTACGTAGCCATGCTCTAGATGTCGAGGGATTCCGGGTCACTGTGAGTGGGGGAGGCAGGGAAGAAGGGCTCACAGGACAGTCAAACCATGCCCCCTGTTTTTCCTTCTTCAAGTAGACCTCTATAAGACAACAGAGACAACTAAGGCTGAGTGGCCAGGCGAGGAGAAACCATCTCGCCGTAAAACATGGAAGGAACACTTCAGGGGAAAGGTGGTATCTCTAAGCAAGAGAACTGAGTGGAGTCAAGGCTGAGAGATGCAGGATAAGCAAATGGGTAGTGAAAAGACATTCATGAGGACAGCTAAAACAATAAGTAATGTAAAATACAGCATAGCAAAACTTTAACCTCCAAATCAAGCCTCTACTTGAATCCTTTTCTGAGGGATGAATAAGGCATAGGCATCAGGGGCTGTTGCCAATGTGCATTAGCTGTTTGCAGCCTCACCTTCTTTCATGGAGT
  Sabatino_pCCVC-TTRm-8003-D3-SPDE-plasmid.fasta:
    - TTCCTACGCGTGTCTGTCTGCACATTTCGTAGAGCGAGTGTTCCGATACTCTAATCTCCCTAGGCAAGGTTCATATTGACTTAGGTTACTTATTCTCCTTTTGTTGACTAAGTCAATAATCAGAATCAGCAGGTTTGGAGTCAGCTTGGCAGGGATCAGCAGCCTGGGTTGGAAGGAGGGGGTATAAAAGCCCCTTCACCAGGAGAAGCCGTCACACAGATCCACAAGCTCCTGCTAGCAGGTAAGTGCCGTGTGTGGTTCCCGCGGGCCTGGCCTCTTTACGGGTTATGGCCCTTGCGTGCCTTGAATTACTGACACTGACATCCACTTTTTCTTTTTCTCCACAGGTTTAAACGCCACCATGCAGATTGAGCTGTCTACTTGTTTTTTTCTGTGCCTGCTGAGGTTCTGCTTCTCTGCCACCAGGAGGTATTACCTGGGGGCTGTGGAGCTGAGCTGGGATTACATGCAGTCTGATCTGGGGGAGCTGCCTGTGGATG
    - TTCCTACACAAAAAACCAACACACAGATCTCTAGAGCTCTGATCTTTTATTGCGGCCGCTCAGTACAGATCCTGGGCCTCACAGCCCAGCACCTCCATCCTCAGGGCAATCTGGTGCACCCAGCTCTGGGGGTGGATCCTCAGGTACCTGGTCAGCAGGGGGGGGTCCAGGCTGTTCACCACTGGGGTGAAGCTATCCTGATTGCCCTGAAACACCTTCACCTTCCCATTCTGGAAGAACAGGGTCCACTGGTGGCCATCCTGGCTGCTGCTAATCAGGAACTCCTTCACATACATGCTGGTCAGCAGGCTTTTCACCCCCTGGGTGGTCACCCCAGTCACTTTCATAGTCTTCTGGAAGTCCACCTGCAGCCACTCCTTGGGGTTGTTCACCTGGGGCCTCCAGGCATTAGACCTGCCCTGCAGATGCAGCCTAGCCTTGCTAGGGCTCCAAGTGGCAAACATATTGGTGAAATAGCTGCTGGCAGTGATCTGGGCATC
