Rscript:           /home/opt/R-3.4.0/lib/R/bin/Rscript
softwareDir:       /home/everett/projects/AAVengeR2
outputDir:         /home/everett/projects/AAVengeRvsIntSiteCaller/210316_MN01490_0011_A000H3FJL2/out
sampleConfigFile:  /home/everett/projects/AAVengeRvsIntSiteCaller/210316_MN01490_0011_A000H3FJL2/sampleData.tsv
modules:
                    - demultiplex.R
                    - prepReads.R
                    - alignReads.R 
                    - buildFragments.R
                    - buildStdFragments.R
                    - buildSites.R
                    - buildMultiHitSites.R
                    - processHIVsites.R
             
#----------------------------------------------------------------------------

demultiplex_outputDir: demultiplex
demultiplex_CPUs: 20
demultiplex_RC_I1_barcodes: FALSE
demultiplex_qualtrim_code: '5'
demultiplex_qualtrim_minLength: 50
demultiplex_anchorReadsFile: /data/sequencing/Illumina-archive/210316_MN01490_0011_A000H3FJL2/Data/Intensities/BaseCalls/Undetermined_S0_R2_001.fastq.gz
demultiplex_adriftReadsFile: /data/sequencing/Illumina-archive/210316_MN01490_0011_A000H3FJL2/Data/Intensities/BaseCalls/Undetermined_S0_R1_001.fastq.gz
demultiplex_index1ReadsFile: /data/sequencing/Illumina-archive/210316_MN01490_0011_A000H3FJL2/Data/Intensities/BaseCalls/Undetermined_S0_I1_001.fastq.gz
demultiplex_correctGolayIndexReads: TRUE
demultiplex_sequenceChunkSize: 100000
demultiplex_index1ReadMaxMismatch: 0
demultiplex_useAdriftReadUniqueLinkers: TRUE
demultiplex_adriftReadLinkerBarcodeMaxMismatch: 1
demultiplex_captureRandomLinkerSeq: TRUE

prepReads_CPUs: 20
prepReads_outputDir: prepReads
prepReads_inputDir:  demultiplex
prepReads_minAnchorReadLength: 40
prepReads_minAdriftReadLength: 30
prepReads_minAlignmentPercentID: 90
prepReads_minAlignmentLength: 15
prepReads_vectorAlignmentTestLength: 25
prepReads_vectorAlignmentTestLength_drift: 2
prepReads_vectorAlignmentChunkSize: 25000
prepReads_HMMmaxStartPos: 3
prepReads_HMMminFullBitScore: 9
prepReads_HMMsearchReadStartPos: 1
prepReads_HMMsearchReadEndPos: 20   # length of HMM + 10%, eg.  17 + ceiling(17*0.10) = 19
prepReads_HMM_F1: 0.020
prepReads_HMM_F2: 0.001
prepReads_HMM_F3: 0.001


alignReads_outputDir: alignReads
alignReads_inputDir:  prepReads/final
alignReads_mapLeaderSequencesOutputFile: prepReads/alignments.rds
alignReads_anchorReadAlignmentsOutputFile: anchorReadAlignments.rds
alignReads_adriftReadAlignmentsOutputFile: adriftReadAlignments.rds
alignReads_CPUs: 10
alignReads_alignmentChunkSize: 25000
alignReads_minAnchorReadLengthPostTrim: 25
alignReads_minAdriftReadLengthPostTrim: 25
alignReads_genomeAlignment_minPercentID: 97
alignReads_genomeAlignment_blatStepSize: 9
alignReads_genomeAlignment_blatTileSize: 11
alignReads_genomeAlignment_anchorRead_maxStartPos:  3     # (!) Maximum alignment start position -- make this a large number for AAV work.
alignReads_genomeAlignment_anchorReadEnd_maxUnaligned: 3  # Max number of NTs at the end of anchor reads not aligning to the genome
alignReads_genomeAlignment_adriftReadEnd_maxUnaligned: 3  # Max number of NTs at the end of adrift reads not aligning to the genome
alignReads_genomeAlignment_anchorReadMinStart: 10
alignReads_genomeAlignment_adriftReadMaxStart: 3

buildFragments_CPUs: 25
buildFragments_outputDir: buildFragments
buildFragments_outputFile: fragments.rds
buildFragments_anchorReadsAlignmentFile: alignReads/anchorReadAlignments.rds
buildFragments_adriftReadsAlignmentFile: alignReads/adriftReadAlignments.rds
buildFragments_idGroup_size: 1000
buildFragments_maxAlignmentsPerRead: 500
buildFragments_minFragLength: 25
buildFragments_maxFragLength: 2500
buildFragments_randomLinkerID_minReadCountToSegreagate: 10
buildFragments_randomLinkerID_minSingleSampleMajorityPercent: 95

buildStdFragments_CPUs: 15
buildStdFragments_outputDir: buildStdFragments
buildStdFragments_outputFile: stdFragments.rds
buildStdFragments_duplicateReadFile: prepReads/duplicateReads.rds
buildStdFragments_standardizeSitesBy: subject
buildStdFragments_standardizeBreaksBy: replicate
buildStdFragments_maxLeaderSeqDiffScore: 0.15
buildStdFragments_representativeSeqCalc_maxReads: 1000
buildStdFragments_representativeSeqCalc_CPUs: 5

#buildSites_excludeSites: chrX,122897024,123043178|chr1,107856070,107856080
buildSites_inputFile: buildStdFragments/stdFragments.rds
buildSites_outputDir: buildSites
buildSites_outputFile: sites.rds
buildSites_assemblyConflictResolution: 0.66

buildMultiHitSites_inputReadsFile: buildFragments/multiHitReads.rds
buildMultiHitSites_inputFragsFile: buildFragments/multiHitFrags.rds
buildMultiHitSites_outputDir:  buildMultiHitSites
buildMultiHitSites_outputFile: multiHitSites.rds

processHIVsites_inputFile: buildSites/sites.rds
processHIVsites_outputDir: processHIVsites
processHIVsites_dualDetectDistance: 3
processHIVsites_dualDetectAubundanceMethod: max # options - max, average
processHIVsites_outputFile: sites.rds

mapSiteLeaderSequences_outputDir:  mapSiteLeaderSequences
mapSiteLeaderSequences_inputFile:  buildSites/sites.rds
mapSiteLeaderSequences_outputFile: sites.rds
mapSiteLeaderSequences_CPUs: 25
mapSiteLeaderSequences_alignmentChunkSize: 10000
mapSiteLeaderSequences_minAlignmentLength: 10
mapSiteLeaderSequences_minAlignmentPercentID: 90

command_python2:     /usr/bin/python2
command_blat:        /home/everett/ext/blat
command_cutadapt:    /usr/local/bin/cutadapt
command_muscle:      /home/everett/ext/muscle
command_makeblastdb: /home/everett/ext/blast+/bin/makeblastdb
command_blastn:      /home/everett/ext/blast+/bin/blastn
command.hmmsearch:   /home/everett/ext/hmmer-3.3.1/bin/hmmsearch
