outputDir:         output
sampleConfigFile:  data/sampleData.tsv

modules:
   - demultiplex
   - prepReads
   - alignReads
   - buildFragments
   - buildStdFragments
   - buildSites
   - annotateRepeats
#   - callNearestGenes
#   - callNearestGenesFiltered
#   - predictPCRartifacts
#   - mapSiteLeaderSequences

# Processing parameters.
#~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

demultiplex_CPUs: 15                                    # Number of CPUs to use for demultiplexing.
demultiplex_outputDir: demultiplex                      # Demultiplexing ouput directory path.
demultiplex_anchorReadsFile: data/combined_R2.fastq.gz  # Anchor read FASTQ path.
demultiplex_adriftReadsFile: data/combined_R1.fastq.gz  # Adrift read FASTQ path.
demultiplex_index1ReadsFile: data/combined_I1.fastq.gz  # I1 barcode read FASTQ path.
demultiplex_RC_I1_barcodes: FALSE                       # Use the reverse compliment of I1 barcode sequences found in [sampleConfigFile].
demultiplex_RC_I1_barcodes_auto: TRUE                   # Attempt to automatically determine best setting for demultiplex_RC_I1_barcodes. Will override [demultiplex_RC_I1_barcodes].
demultiplex_qualtrim_code: '5'                          # ASCII Q-score threshold to fail sliding window read quality trimming.
demultiplex_qualtrim_minLength: 50                      # Minimum length of anchor and adrift reads post quality trimming.
demultiplex_correctGolayIndexReads: TRUE                # Correct Golay barcodes using Golay alogrithm. 
demultiplex_sequenceChunkSize: 100000                   # Chunk size to use when breaking sequencing data into chunks for parallel processing.
demultiplex_index1ReadMaxMismatch: 1                    # Max. number of mismatches allowed in I1 barcodes.
demultiplex_adriftReadLinkerBarcodeMaxMismatch: 1       # Max. number of mismatches allowed in R1 unique linker sequences.
demultiplex_anchorRead.startSeq.maxMisMatch: 1          # Max. number of mismatches allowed in anchor read start sequences [if provided in sampleDetails file].
demultiplex_useAdriftReadUniqueLinkers: TRUE            # Use unique adrift read linker sequences when demultiplexing. 

prepReads_CPUs: 15                                      # Number of CPUs to use when preparing reads for alignment to thegenome.
prepReads_outputDir: prepReads                          # PrepReads ouput directory path.
prepReads_readsTable:  demultiplex/reads.rds
prepReads_excludeAnchorReadVectorHits: FALSE
prepReads_excludeAdriftReadVectorHits: FALSE
prepReads_vectorAlignmentTestLength: 25
prepReads_vectorAlignmentTest_minPercentCoverage: 90
prepReads_vectorAlignmentTest_minPercentID: 90
prepReads_HMMsearchReadStartPos: 1
prepReads_HMMsearchReadEndPos:  16
prepReads_HMMmaxStartPos: 3
prepReads_HMMminFullBitScore: 5
prepReads_minAnchorReadLength: 30
prepReads_minAdriftReadLength: 30
prepReads_mapLeaderSeqsMinAlignmentLength: 15
prepReads_mapLeaderSeqsMinPercentID: 90
prepReads_buildReadMaps_blastReconstruction: TRUE
prepReads_buildReadMaps_minMapStartPostion: 5

alignReads_CPUs: 15
alignReads_outputDir: alignReads                           # AlignReads ouput directory path.
alignReads_inputFile: prepReads/reads.rds                  # Path to input reads RDS file.
alignReads_genomeAlignment_anchorRead_maxStartPos: 3       # (!) Set to a small value such as 3 when using HMMs, large value such as 100 for AAV analyses.
alignReads_genomeAlignment_minPercentID: 98                # Min. % seq id required to accept an alignment to the reference genome.
alignReads_genomeAlignment_blatStepSize: 9                 # BLAT step size parameter. BLAT default 9.
alignReads_genomeAlignment_blatTileSize: 11                # BLAT tile size parameter. BLAT default 11.
alignReads_genomeAlignment_repMatch: 2500                  # BLAT repMatch parameter. Number of times a tile needs to be seen before masking. 
alignReads_genomeAlignment_anchorReadEnd_maxUnaligned: 3   # Max. number of NTs at the end of anchor reads not aligning to the genome.
alignReads_genomeAlignment_adriftReadEnd_maxUnaligned: 10  # Max. number of NTs at the end of adrift reads not aligning to the genome. 
alignReads_genomeAlignment_adriftReadMaxStart: 3           # Max. query sequence start position for alignments to the reference genome. 

buildFragments_CPUs: 15
buildFragments_outputDir: buildFragments
buildFragments_duplicateReadFile: prepReads/duplicateReads.rds
buildFragments_anchorReadsAlignmentFile: alignReads/anchorReadAlignments.rds
buildFragments_adriftReadsAlignmentFile: alignReads/adriftReadAlignments.rds
buildFragments_idGroup_size: 1000
buildFragments_maxReadAlignments: 1000
buildFragments_minFragLength: 20
buildFragments_maxFragLength: 2500
buildFragments_randomLinkerID_minReadCountToSegreagate: 10
buildFragments_randomLinkerID_minSingleSampleMajorityPercent: 90

buildStdFragments_CPUs: 15
buildStdFragments_minReadsPerFrag: 1
buildStdFragments_createMultiHitClusters: TRUE
buildStdFragments_inputFiles: buildFragments/fragments.rds
buildStdFragments_outputDir: buildStdFragments
buildStdFragments_representativeSeqCalc_maxReads: 1000
buildStdFragments_representativeSeqCalc_CPUs: 5
buildStdFragments_categorize_anchorReadRemnants_stepSize: 12
buildStdFragments_UMI_conflict_minPercentReads: 75

buildSites_inputFile: buildStdFragments/stdFragments.rds
buildSites_outputDir: buildSites

annotateRepeats_CPUs: 15
annotateRepeats_inputFile: buildSites/sites.rds
annotateRepeats_outputDir: annotateRepeats
annotateRepeats_addAfter: posid

predictPCRartifacts_CPUs: 15
predictPCRartifacts_inputFile: annotateRepeats/sites.rds
predictPCRartifacts_outputDir: predictPCRartifacts
predictPCRartifacts_outputFile: sites.rds
predictPCRartifacts_addAfter: nRepsObs
predictPCRartifacts_adjacentSeqLength: 15
predictPCRartifacts_minAlignmentLength: 12
predictPCRartifacts_minPercentSeqID: 80

callNearestGenes_CPUs: 15
callNearestGenes_inputFile: callNearestGenesFiltered/sites.rds
callNearestGenes_outputDir: callNearestGenes
callNearestGenes_outputFile: sites.rds
callNearestGenes_addAfter: nRepsObs
callNearestGenes_TU_position: either
callNearestGenes_boundaries:
  hg38:
    TUs:   hg38.TUs.rds
    exons: hg38.exons.rds
  sacCer3:
        TUs:   sacCer3.TUs.rds
        exons: sacCer3.exons.rds
  canFam3:
        TUs:   canFam3.humanXeno.TUs.rds
        exons: canFam3.humanXeno.exons.rds
  macFas5:
        TUs:   macFas5.humanXeno.TUs.rds
        exons: macFas5.humanXeno.exons.rds


callNearestGenesFiltered_CPUs: 15
callNearestGenesFiltered_columnPrefix: oncoGenes
callNearestGenesFiltered_inputFile: buildSites/sites.rds
callNearestGenesFiltered_outputDir: callNearestGenesFiltered
callNearestGenesFiltered_outputFile: sites.rds
callNearestGenesFiltered_addAfter: nRepsObs
callNearestGenesFiltered_TU_position: either
callNearestGenesFiltered_boundaries:
  hg38:
    TUs:   hg38.TUs.rds
    exons: hg38.exons.rds
    filter: hg38.Bushman.oncoGeneList.rds
  sacCer3:
        TUs:   sacCer3.TUs.rds
        exons: sacCer3.exons.rds
        filter: hg38.Bushman.oncoGeneList.rds
  canFam3:
        TUs: canFam3.humanXeno.TUs.rds
        exons: canFam3.humanXeno.exons.rds
        filter: hg38.Bushman.oncoGeneList.rds
  macFas5:
        TUs:   macFas5.humanXeno.TUs.rds
        exons: macFas5.humanXeno.exons.rds
        filter: hg38.Bushman.oncoGeneList.rds
        
        
mapSiteLeaderSequences_CPUs: 15
mapSiteLeaderSequences_outputDir: mapSiteLeaderSequences
mapSiteLeaderSequences_inputFile: callNearestGenes/sites.rds
mapSiteLeaderSequences_addAfter: repLeaderSeq
mapSiteLeaderSequences_minAllowableGap: 5                   # Min. space between blast hits allowed. Larger gaps will be filled with [x].
mapSiteLeaderSequences_alignmentChunkSize: 5000
mapSiteLeaderSequences_minAlignmentPercentID: 90
mapSiteLeaderSequences_minAlignmentLength: 15
mapSiteLeaderSequences_outputFile: sites.rds


# Software environment.
#~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~

command_python2:     /usr/bin/python2
command_blat:        /home/ubuntu/software/blat
command_cutadapt:    /usr/bin/cutadapt
command_muscle:      /home/ubuntu/software/muscle
command_makeblastdb: /home/ubuntu/software/ncbi-blast-2.12.0+/bin/makeblastdb
command_blastn:      /home/ubuntu/software/ncbi-blast-2.12.0+/bin/blastn
command.hmmsearch:   /home/ubuntu/software/hmmer-3.3.2/bin/hmmsearch

Rscript:             /usr/bin/Rscript
softwareDir:         /home/ubuntu/software/AAVengeR
